name: Build and Push Docker Image

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
      
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag jcazolag/express-randomquotes:latest
      

    
    - name: Push Docker image
      run: docker push jcazolag/express-randomquotes:latest
